# -*- coding: utf-8 -*-
"""Homework 3 - 快速排序演算法實作

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18geYqVXAuIxYWiCqQrRkFCjzZ-qLFK8I
"""

def swap(arr, i, j):
    arr[i], arr[j] = arr[j], arr[i]

def partition(arr, low, high):
    pivot = arr[high]
    i = low - 1

    for j in range(low, high):
        if arr[j] < pivot:
            i += 1
            swap(arr, i, j)
            print(f"交換元素: {arr}")

    swap(arr, i + 1, high)
    print(f"交換樞紐: {arr}")
    return i + 1

def quick_sort(arr, low, high):
    if low < high:
        p = partition(arr, low, high)
        print(f"分割點: {p}, 當前數組狀態: {arr}")

        quick_sort(arr, low, p - 1)
        quick_sort(arr, p + 1, high)

if __name__ == "__main__":
    user_input = input("請輸入要排序的數字，以空格分隔: ")
    arr = list(map(int, user_input.split()))

    print("未排序數組:", arr)

    quick_sort(arr, 0, len(arr) - 1)

    print("已排序數組:", arr)